# Generated by Django 5.0.6 on 2024-05-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_role_role_name_alter_user_email_consultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist')], default='patient', max_length=255, unique=True),
        ),
    ]
