# Generated by Django 5.0.6 on 2024-05-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_consultation_unique_patient_officer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultation',
            name='unique_patient_practitioner',
        ),
    ]
